<?php
	//https://inviqa.com/blog/using-knockout-js-magento-2
	//http://knockoutjs.com/documentation/value-binding.html


	$installedBlocks = $this->registry->registry('installed_block_types');
?>
<div class="mage25-ui">

	<div  id="mage25_main_div">
			
			<?php if(sizeof($installedBlocks) == 0){ ?>
				<p><button type="button" class="btn btn-danger mage25_system_block_install_button" onclick="mage25_InstallSystemBlocks();"><?php echo __('Install System Blocks'); ?></button>
				</p>
			<?php } ?>

			<table class="table table-bordered" id="installed_blocks_table">

			<thead>
				<tr class="info">
					<th>
							<?php echo __('Title'); ?>
					</th>
					<th>
							<?php echo __('Module/Vendor Block Path'); ?>
					</th>
					<th>
							<?php echo __('Block Name'); ?>
					</th>
					<th>
							<?php echo __('Actions'); ?>
					</th>
				</tr>

			</thead>
			<tbody>
<!-- Loop for showing installed blocks -->
					<?php foreach($installedBlocks as $k){ ?>
					<tr>
							<td><?php echo $k['btName']; ?></td>
							<td><p><?php echo $k['btDescription']; ?></p><p><?php echo $k['btHandle']; ?></p></td>
							<td><?php echo $k['btName']; ?></td>
							<td><button type="button" class="btn btn-success" title="<?php echo __("Other vendor Custom Templates"); ?>" onclick="mage25_AssignCustomTemplates('<?php echo $k['btID']; ?>');"><i class="fa fa-file"></i></button>&nbsp;&nbsp;<button type="button" class="btn btn-info" title="<?php echo __("Refresh Block Type"); ?>" onclick="mage25_RefreshBlockType('<?php echo $k['btID']; ?>');"><i class="fa fa-refresh"></i></button>&nbsp;&nbsp;<button type="button" class="btn btn-danger" onclick="mage25_RemoveBlockType('<?php echo $k['btID']; ?>');" title="<?php echo __("Remove Block Type"); ?>"><i class="fa fa-trash"></i></button></td>

					</tr>
					<?php } ?>
					
					
					
			</tbody>
			<tfoot>
	<tr class="warning">
			<td colspan="3"><div class="input"><input type="text" class="form-control mage25-input-text" placeholder="<?php echo __('[\]Vendor\Module\Block\[Blockhandle]'); ?>" id="mageblockhandle"  /></div></td>

			<td><button type="button" class="btn btn-primary" onclick="mage25_insertBlockType();"><?php echo __('Add Block Type'); ?></button></td>

	</tr>
			</tfoot>

			</table>
	</div>
</div>

<script type="text/javascript">

require(['jquery'], function($) {
	mage25_AssignCustomTemplates = function(btID){
		var data = {action:'block_custom_templates_other_vendor','btID':btID};
		mage25_loadModel("Other vendors Custom Templates", DIRNAME_APP+'/mage25/blocks/add','POST', data);
	}
	mage25_InstallSystemBlocks = function(){
	
		var data = {action:'block_mass_install'};

		var url = mage25_getControllerUrl('/mage25/blocks/add');
		mage25_showLoader();
		$.ajax( {
			    url: url,
			    data: data,
			    type: 'POST'
			}).done(function(ajaxContent) {

				var obj = $.parseJSON(ajaxContent);

				
				mage25_showBlockTypesTable(obj.installed_blocks);
				if(obj.success == 1){

					mage25_showGlobalMessageDiv(obj.message, 'success');
				}else{
					mage25_showGlobalMessageDiv(obj.message, 'danger');
				}
				
				mage25_hideLoader();
				$(".mage25_system_block_install_button").remove();

			}).fail(function( jqXHR, textStatus ) {

			  mage25_showGlobalMessageDiv(jqXHR.responseText, 'danger');
			  mage25_hideLoader();
		});
		
		
		
		
	
	}
	
	
	
	mage25_insertBlockType = function(){

		var blockHandle = $('#mageblockhandle').val();
		//alert(blockHandle);
		var data = {action:'block_add', block_class:blockHandle};

		var url = mage25_getControllerUrl('/mage25/blocks/add');
		
		mage25_showLoader();
		$.ajax( {
			    url: url,
			    data: data,
			    type: 'POST'
			}).done(function(ajaxContent) {

				var obj = $.parseJSON(ajaxContent);

				//alert(obj.message);
				mage25_showBlockTypesTable(obj.installed_blocks);
				if(obj.success == 1){

					mage25_showGlobalMessageDiv(obj.message, 'success');
				}else{
					mage25_showGlobalMessageDiv(obj.message, 'danger');
				}
				
				mage25_hideLoader();

			}).fail(function( jqXHR, textStatus ) {

			  mage25_showGlobalMessageDiv(jqXHR.responseText, 'danger');
			  mage25_hideLoader();
			});
	}


	mage25_RefreshBlockType = function(btID){
		var data = {action:'block_refresh', block_id:btID};

		var url = mage25_getControllerUrl('/mage25/blocks/add');
		mage25_showLoader();
		
		
		$.ajax( {
			    url: url,
			    data: data,
			    type: 'POST'
			}).done(function(ajaxContent) {

				var obj = $.parseJSON(ajaxContent);

				//alert(obj.message);
				mage25_showBlockTypesTable(obj.installed_blocks);
				if(obj.success == 1){

					mage25_showGlobalMessageDiv(obj.message, 'success');
					
				}else{
					mage25_showGlobalMessageDiv(obj.message, 'danger');
				}
				
				mage25_hideLoader();

			}).fail(function( jqXHR, textStatus ) {

			 
			  mage25_showGlobalMessageDiv(jqXHR.responseText, 'danger');
			  mage25_hideLoader();

			  
			});
	}
	
	mage25_RemoveBlockType = function(btID){
		
		if(!confirm("<?php echo __("Are you sure do you want to delete this block type?"); ?>")) return false;
		
		var data = {action:'remove_block', block_id:btID};

		var url = mage25_getControllerUrl('/mage25/blocks/add');
		
		mage25_showLoader();
		
		$.ajax( {
			    url: url,
			    data: data,
			    type: 'POST'
			}).done(function(ajaxContent) {

				var obj = $.parseJSON(ajaxContent);

				//alert(obj.message);
				
				mage25_showBlockTypesTable(obj.installed_blocks);

				if(obj.success == 1){

					
					mage25_showGlobalMessageDiv(obj.message, 'success');
				}else{
					mage25_showGlobalMessageDiv(obj.message, 'danger');
				}

				mage25_hideLoader();
				
			}).fail(function( jqXHR, textStatus ) {

			  mage25_showGlobalMessageDiv(jqXHR.responseText, 'danger');
			  
			  mage25_hideLoader();
			  
			});
	}
	
	mage25_showBlockTypesTable = function(data){
		var contents = '';
		$.each(data, function(i,item) {
		    contents=contents+"<tr>";
		    contents=contents+"<td>"+item.btName+"</td>";
		    contents=contents+"<td><p>"+item.btDescription+"</p><p>"+item.btHandle+"</p></td>";
		    contents=contents+"<td>"+item.btName+"</td>";
		    contents=contents+"<td><button title=\"<?php echo __("Other vendor Custom Templates"); ?>\" type=\"button\" class=\"btn btn-success\" onclick=\"mage25_AssignCustomTemplates('"+item.btID+"');\"><i class=\"fa fa-file\"></i></button>&nbsp;&nbsp;<button title=\"<?php echo __("Refresh Block Type"); ?>\" type=\"button\" class=\"btn btn-info\" onclick=\"mage25_RefreshBlockType('"+item.btID+"');\"><i class=\"fa fa-refresh\"></i></button>&nbsp;&nbsp;<button title=\"<?php echo __("Remove Block Type"); ?>\" type=\"button\" class=\"btn btn-danger\" onclick=\"mage25_RemoveBlockType('"+item.btID+"');\"><i class=\"fa fa-trash\"></i></button></td>";
		});
		
		$("#installed_blocks_table tbody").html(contents);

			
	}


});


</script>