
<textarea name="content" class="mage25_tiny_mce mage25-advanced-editor"><?php if(isset($blockData['content'])){ echo $blockData['content']; } ?></textarea>






<script type="text/javascript">
require(['jquery'], function($){
	$(document).ready(function(){
		mage25_activateTinyMCEEditor("mage25-advanced-editor");
		//mage25_activateTinyMCEEditor("mage25-advanced-editor-1");
	});
});
</script>
	
	