<?php 
$stdWidth = $width > 0 ?$width :400;
$stdHeight  = $height >0 ? $height : 400;	
 ?>	
 <style>
 .googleMapCanvas{
 	height:<?php echo $height; ?>px !important;
	width:<?php echo $width; ?>px !important;
 }
 </style>
 
	<?php if( strlen($title)>0){ ?><h3><?php echo $title?></h3><?php } ?>
	<div id="googleMapCanvas<?php echo $bID?>" class="googleMapCanvas" ></div>	
    
    
    <?php
		echo ('<script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true"></script>');
				echo ('<script type="text/javascript"> 
				require([\'jquery\'], function ($) {
				function googleMapInit' . $bID . '() { 
				   try{
					  var latlng = new google.maps.LatLng(' . $latitude . ', ' . $longitude . ');
					   var mapOptions = {
						 zoom: ' . $zoom . ',
						 center: latlng,
						 mapTypeId: google.maps.MapTypeId.ROADMAP,
						 streetViewControl: false,
						 mapTypeControl: false
					  };
					   var map = new google.maps.Map(document.getElementById(\'googleMapCanvas' . $bID . '\'), mapOptions);
					   var marker = new google.maps.Marker({
						   position: latlng, 
						   map: map
					   });
				   }catch(e){
				   jQuery("#googleMapCanvas'. $bID .'").replaceWith("<p>Unable to display map: "+e.message+"</p>")}
				}
				jQuery(function() {
					var t;
					var startWhenVisible = function (){
						if (jQuery("#googleMapCanvas'. $bID .'").is(":visible")){
							window.clearInterval(t);
							googleMapInit' . $bID . '();
							return true;
						} 
						return false;
					};
					if (!startWhenVisible()){
						t = window.setInterval(function(){startWhenVisible();},100);      
					}
				});   
				});         
				</script>');
				?>
    
    
