<link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('Magento_Theme::css/slick.css') ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('Magento_Theme::css/slick-theme.css') ?>">

<div class="slick_arrows">


    <span class="control-prev"><< Prev</span>
    <span class="control-next"> Next >> </span>

</div>
<?php

echo '<div class="slider">';
if ($slideshow_type == 'CUSTOM') {
    $savedSlides = $blockObject->getSlides($bID);
    echo "<div class='mage25_slideshow_div' id='mage25_slideshow_div_" . $bID . "'>";
    $i = 1;
    foreach ($savedSlides as $_slides) {
        echo "<div class='mage25_slideshow_items'>";
        if ($_slides['fID'] > 0) {
            $fileData = $this->getFileByID($_slides['fID']);
            $imagePath = $this->getImageForView($_slides['fID']);
            $title = $_slides['title'];
            $description = $_slides['description'];
            $target = $_slides['target'];
            $link_text = $_slides['link_text'];
            $linkToUrl = '';

            if ($_slides['link_type'] == 1) {
                $pageID = $_slides['page_id'];
                $linkToUrl = $this->getLink($pageID);
            }

            if ($_slides['link_type'] == 2 and trim($_slides['external_link']) != '') {
                $linkToUrl = $_slides['external_link'];
            }

            echo "<div class='mage25_img_div'>";
            if ($linkToUrl != '') {
                echo "<a href='" . $linkToUrl . "' target='" . $target . "' title='" . $title . "'>";
            }

            echo "<img src='" . $imagePath . "' title='" . $title . "' alt='" . $title . "'>";


            if ($linkToUrl != '') {
                echo "</a>";
            }

            echo "</div>";

            echo "<div class='mage25_content'>";

            if (trim($title) != '') {
                echo "<div class='mage25_img_title'>" . $title . "</div>";
            }

            if (trim($description) != '') {
                echo "<div class='mage25_img_desc'>" . $description . "</div>";
            }

            echo '<a href="#">Shop Now</a>';

            if ($linkToUrl != '' and trim($link_text) != '') {
                echo "<a href='" . $linkToUrl . "' target='" . $target . "' title='" . $title . "'>";
                echo $link_text;
                echo "</a>";
            }

            echo "</div>";
        }
        echo "</div>";
        $i++;
    }
    echo "</div>";
} else {
    $savedSlides = $blockObject->getFilesByfsID($fsID);

    echo "<div class='mage25_slideshow_div' id='mage25_slideshow_div_" . $bID . "'>";
    foreach ($savedSlides as $_slides) {
        $_slides = $this->getFileByID($_slides['fID']);
        $imagePath = $this->getImageForView($_slides['fID']);
        echo "<div class='mage25_slideshow_items'>";
        echo "<div class='mage25_img_div'>";
        echo "<img src='" . $imagePath . "' title='" . $_slides['fName'] . "' alt='" . $_slides['fName'] . "'>";
        echo "</div>";
        echo "</div>";
    }
    echo "</div>";
}
echo "</div>";
?>


<script type="application/javascript">
    require([
        'jquery',
        'slick'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery("#mage25_slideshow_div_<?php echo $bID; ?>").slick({

                dots: true,

                // prevArrow: '<span class="slickArrow slickArrow--prev"></span>',
                // nextArrow: '<span class="slickArrow slickArrow--next"></span>'

                nextArrow: '.control-next',
                prevArrow: '.control-prev'

            });

        });
    });
</script>




